---
- name: Check git-credential-manager
  package_facts:
    manager: auto

---
- name: Install git-credential-manager
  block:
    - name: Download git-credential-manager deb
      get_url:
        url: "https://github.com/git-ecosystem/git-credential-manager/releases/download/v2.8.0/gcm-linux-x64-2.8.0.deb"
        dest: "/tmp/git_credential.deb"
        mode: '0644'

    - name: Install git-credential-manager deb
      become: yes
      apt:
        deb: "/tmp/git_credential.deb"
        state: present

    - name: Remove downloaded deb
      file:
        path: "/tmp/git_credential.deb"
        state: absent


  when: "'git-credential-manager' not in ansible_facts.packages"
