---
- name: Install sourcegit
  include_role:
    name: download_to_location
  vars:
    url: "https://github.com/sourcegit-scm/sourcegit/releases/download/v2026.12/sourcegit-2026.12.linux.amd64.AppImage"
    destination: "/opt/sourcegit"
    appname: "sourcegit.AppImage"
