---
- name: Install qownnotes
  include_role:
    name: download_to_location
  vars:
    url: "https://github.com/pbek/QOwnNotes/releases/latest/download/QOwnNotes-x86_64.AppImage"
    destination: "/opt/qownnotes"
    appname: "QOwnNotes-x86_64.AppImage"
