---
- name: Stowing dotfiles
  block:
    - name: Collect dotfiles for stow
      listen: restow dotfiles
      find:
        paths: "{{ ansible_env.HOME }}/.dotfiles"
        file_type: directory
        depth: 1
      register: pkg_dirs


    - name: Build package list (exclude [.]folders)
      listen: restow dotfiles
      set_fact:
        stow_packages: >-
          {{ pkg_dirs.files
              | map(attribute='path')
              | map('basename')
              | reject('match','^\\.')
              | list }}


    - name: Stow collected dotfiles
      listen: restow dotfiles
      command:
        argv:
          - stow
          - --restow
          - --dir
          - "{{ ansible_env.HOME }}/.dotfiles"
          - --target
          - "{{ ansible_env.HOME }}"
          - "{{ item }}"
          - --verbose=2
      loop: "{{ stow_packages }}"
      register: stow_result
      changed_when: >-
        ('LINK:' in stow_result.stdout) or
        ('LINK:' in stow_result.stderr)
