---
- name: Ensure KeePass directory exists
  become: true
  file:
    path: /opt/keepassxc
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"


- name: Install KeePassXC
  block:
    - name: Download KeePassXC AppImage
      get_url:
        url: https://github.com/keepassxreboot/keepassxc/releases/download/2.7.12/KeePassXC-2.7.12-x86_64.AppImage
        dest: /opt/keepassxc/keepassxc.AppImage
        timeout: 120
        mode: '0755'
