---
- name: Check smplayer
  stat:
    path: /opt/smplayer/smplayer.AppImage
  register: install_binary


- name: Install smplayer
  block:
    - name: Ensure smplayer directory
      become: true
      file:
        path: /opt/smplayer
        state: directory
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_gid }}"

    - name: Download smplayer
      get_url:
        url: https://github.com/smplayer-dev/smplayer/releases/download/v25.6.0/SMPlayer-25.6.0-x86_64.AppImage
        dest: /opt/smplayer/smplayer.AppImage
        mode: '0755'

  when: not install_binary.stat.exists
