options nvidia NVreg_EnableS0ixPowerManagement=0

# required for suspend to store things in VRAM
options nvidia NVreg_PreserveVideoMemoryAllocations=1 NVreg_TemporaryFilePath=/var/tmp

# less aggressive power manangement
options nvidia NVreg_DynamicPowerManagement=0x03