---
- name: Install packages
  become: true
  apt:
    pkg:
      - stow
    state: present


- name: "[TRANSIENT] Remove files that are replaced by stow"
  loop:
    - .bashrc
    - .profile
  file:
    path: "{{ ansible_env.HOME }}/{{ item }}"
    state: absent


- name: Collect dotfiles for stow
  find:
    paths: "{{ ansible_env.HOME }}/.dotfiles"
    file_type: directory
    depth: 1
  register: pkg_dirs


- name: Build package list (exclude hidden like .git)
  set_fact:
    stow_packages: >-
      {{ pkg_dirs.files
          | map(attribute='path')
          | map('basename')
          | reject('match','^\\.')
          | list }}


- name: Stow collected dotfiles
  command:
    argv:
      - stow
      - --restow
      - --dir
      - "{{ ansible_env.HOME }}/.dotfiles"
      - --target
      - "{{ ansible_env.HOME }}"
      - "{{ item }}"
      - --verbose=2
  loop: "{{ stow_packages }}"
  register: stow_result
  changed_when: >-
    ('LINK:' in stow_result.stdout) or
    ('LINK:' in stow_result.stderr)
