---
- name: Install fblog
  include_role:
    name: download_to_location
  vars:
    url: "https://github.com/brocode/fblog/releases/download/v4.17.0/fblog"
    destination: "{{ ansible_env.HOME }}/.local/bin"
    appname: "fblog"


- name: Install difftastic
  include_role:
    name: download_to_location
  vars:
    install_type: "archive"
    url: "https://github.com/Wilfred/difftastic/releases/download/{{ diffstatic_version }}/difft-x86_64-unknown-linux-gnu.tar.gz"
    destination: "{{ ansible_env.HOME }}/.local/bin"
    appname: "difft"
    archive_extra_opts:
      - "difft"