---
- name: Gathering user
  set_fact:
    user: "{{ ansible_facts.env.SUDO_USER | default(ansible_facts.env.USER) }}"


- name: Gather folder structure of dotfiles
  find:
    paths: "{{ playbook_dir }}/templates"
    file_type: directory
    recurse: true
    hidden: yes
  register: found_folders


- name: Gather templated dotfiles
  find:
    paths: "{{ playbook_dir }}/templates"
    file_type: file
    recurse: true
    hidden: true
  register: found_files


- name: Preparing dotfiles folder under ~/.config 
  set_fact:
    dotfiles_exclude_folders:
      - stow


- name: Gather dotfiles folders
  set_fact:
    dotfiles_folders: >-
      {{
        (
          lookup('ansible.builtin.filetree', 'templates/', wantlist=True)
          | selectattr('state', 'equalto', 'directory')
          | map(attribute='path')
          | map('split', '/')
          | map('first')
          | unique
          | difference(dotfiles_exclude_folders | default([]))
        )
      }}


- name: Gather files under dotfiles folder
  set_fact:
    dotfiles_items: >-
      {{
        (dotfiles_items | default([]))
        +
        (
          lookup('ansible.builtin.filetree', 'templates/' ~ folder_name, wantlist=True)
          | map('combine', {'folder_name': folder_name})
          | list
        )
      }}
  loop: "{{ dotfiles_folders }}"
  loop_control:
    loop_var: folder_name


- name: Ensure dotfiles folders exist under ~/.dotfiles
  become_user: "{{ user }}"
  file:
    path: "/home/{{ user }}/.dotfiles/{{ folder_name }}"
    state: directory
  loop: "{{ dotfiles_folders }}"
  loop_control:
    loop_var: folder_name


- name: Ensure stow ignores exists
  become_user: "{{ user }}"
  copy:
    src: "templates/stow/.stow-local-ignore"
    dest: "/home/{{ user }}/.dotfiles/.stow-local-ignore"


- name: Generate configs (folder only)
  become_user: "{{ user }}"
  file:
    path: "/home/{{ user }}/.dotfiles/{{ item.folder_name }}/{{ item.path }}"
    state: directory
  loop: "{{ dotfiles_items }}"
  when: item.state == 'directory'
  loop_control:
    label: "~/{{ item.folder_name }}/{{ item.path }}"


- name: Generate configs (files from template)
  become_user: "{{ user }}"
  template:
    src: "{{ item.src }}"
    dest: "/home/{{ user }}/.dotfiles/{{ item.folder_name }}/{{ item.path }}"
  loop: "{{ dotfiles_items }}"
  when: item.state == 'file'
  loop_control:
    label: "~/{{ item.folder_name }}/{{ item.path }}"
