---
- name: Gathering user
  set_fact:
    user: "{{ ansible_facts.env.SUDO_USER | default(ansible_facts.env.USER) }}"


- name: Preparing dotfiles folder under ~/.config 
  set_fact:
    dotfiles_exclude_folders:
      - stow


- name: Gather dotfiles folders
  set_fact:
    dotfiles_folders: >-
      {{
        (
          lookup('ansible.builtin.filetree', 'templates/', wantlist=True)
          | selectattr('state', 'equalto', 'directory')
          | map(attribute='path')
          | map('split', '/')
          | map('first')
          | unique
          | difference(dotfiles_exclude_folders | default([]))
        )
      }}

- name: Gather private dotfiles folders
  set_fact:
    private_dotfiles_folders: >-
      {{
        (
          lookup(
            'ansible.builtin.filetree',
            'private_data/roles/',
            wantlist=True,
            errors='ignore'
          )
          | default([], true)
        )
        | selectattr('state', 'equalto', 'directory')
        | map(attribute='path')
        | select('match', '^[^/]+/templates/stow$')
        | map('split', '/')
        | map('first')
        | unique
        | list
      }}


- name: Ensure dotfiles folders exist under ~/.dotfiles
  become_user: "{{ user }}"
  file:
    path: "/home/{{ user }}/.dotfiles/{{ folder_name }}"
    state: directory
  loop: "{{ dotfiles_folders }}"
  loop_control:
    loop_var: folder_name


- name: Ensure stow ignores exists
  become_user: "{{ user }}"
  copy:
    src: "templates/stow/.stow-local-ignore"
    dest: "/home/{{ user }}/.dotfiles/.stow-local-ignore"

- name: Generate public dotfiles packages
  include_role:
    name: stow_package
  vars:
    package_name: "{{ package_folder }}"
    private_data: false
    file_mode: null
    hide_output: false
  loop: "{{ dotfiles_folders }}"
  loop_control:
    loop_var: package_folder

- name: Generate private dotfiles packages
  include_role:
    name: stow_package
  vars:
    package_name: "{{ package_folder }}"
    private_data: true
    load_vars: true
  loop: "{{ private_dotfiles_folders }}"
  loop_control:
    loop_var: package_folder
