---
- name: Gathering user
  set_fact:
    user: "{{ ansible_facts.env.SUDO_USER | default(ansible_facts.env.USER) }}"


# - name: Gather templated dotfiles
#   find:
#     paths: "templates"
#     file_type: file
#     hidden: yes
#   register: found_files

- name: Gather folder structure of dotfiles
  find:
    paths: "{{ playbook_dir }}/templates"
    file_type: directory
    recurse: true
    hidden: yes
  register: found_folders


- name: Gather templated dotfiles
  find:
    paths: "{{ playbook_dir }}/templates"
    file_type: file
    recurse: true
    hidden: true
  register: found_files

#
# @note: make sure our cloned files are in LF endings
#
- name: "[TRANSIENT] Apply LF endings"
  replace:
    path: "{{ item.path }}"
    regexp: "\r$"
    replace: ""
  loop: "{{ found_files.files | default([]) }}"
  loop_control:
    label: "{{ item.path }}"


- name: Ensure ~/.dotfiles directory exists
  file:
    path: "/home/{{ user }}/.dotfiles/"
    state: directory


- name: Mirroring dotfiles folder structure under ~/.dotfiles
  file:
    path: >-
      {{ item.path
         | regex_replace(
             '^' ~ ((playbook_dir ~ '/templates') | regex_escape),
             (ansible_env.HOME ~ '/.dotfiles')
           )
      }}
    state: directory
  loop: "{{ found_folders.files }}"
  loop_control:
    label: >-                                   # output: src_path -> dest_path
      ./{{ item.path | relpath(playbook_dir) }}
      -> ~/.dotfiles/{{ item.path | relpath(playbook_dir ~ '/templates') }}


- name: Generate templated dotfiles
  become_user: "{{ user }}"
  template:
    src: "{{ item }}"
    dest: "/home/{{ user }}/.dotfiles/{{ item }}"
  loop:

    # core configs
    - ".stow-local-ignore"
    - "profile/.bashrc"
    - "profile/.profile"
    - "profile/.inputrc"
    - "profile/.hushlogin"
    - "xresources/.Xresources"

    # git config
    - "git/.gitconfig"

    # tmux config
    - "tmux/.tmux.conf"
  loop_control:
    label: "~/.dotfiles/{{ item }}"


#
#  Neovim configs
#
- name: Generate Neovim configs (folder only)
  become_user: "{{ user }}"
  file:
    path: "/home/{{ user }}/.dotfiles/{{ folder_name }}/{{ item.path }}"
    state: directory
  with_filetree: "templates/{{ folder_name }}"
  vars:
    folder_name: "nvim"
  when: item.state == 'directory'
  loop_control:
    label: "~/{{ item.path }}"

- name: Generate Neovim configs (files from template)
  become_user: "{{ user }}"
  template:
    src: "{{ item.src }}"
    dest: "/home/{{ user }}/.dotfiles/{{ folder_name }}/{{ item.path }}"
  with_filetree: "templates/{{ folder_name }}"
  vars:
    folder_name: "nvim"
  when: item.state == 'file'
  loop_control:
    label: "~/{{ item.path }}"