---
- name: Gathering user
  set_fact:
    user: "{{ ansible_facts.env.SUDO_USER | default(ansible_facts.env.USER) }}"


- name: Copy all maven scripts
  copy:
    src: "{{ role_path }}/scripts/"
    dest: "/home/{{ user }}/.local/bin/"
    mode: 0755


- name: Check templates dir exists
  stat:
    path: "private_data/roles/{{ role_path | basename }}/templates"
  register: dir_private_data


- name: Gather templated files
  set_fact:
    file_templates: >-
      {{
        lookup(
          'ansible.builtin.filetree',
          'private_data/roles/' ~ (role_path | basename) ~ '/templates',
          wantlist=True
        )
        | map('combine', {'folder_name': (role_path | basename)})
        | list
      }}
  when: dir_private_data.stat.exists


- name: Load configuration files
  include_vars:
    file: "private_data/roles/{{ role_path | basename }}/vars/env.yml"
  when: dir_private_data.stat.exists


- name: Check templates dir exists
  stat:
    path: "private_data/roles/{{ role_path | basename }}/templates"
  register: dir_templates

- name: Generate configs (folder only)
  file:
    path: "/home/{{ user }}/.dotfiles/{{ item.folder_name }}/{{ item.path }}"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
  loop: "{{ (file_templates | default([])) | selectattr('state', 'equalto', 'directory') | list }}"
  loop_control:
    label: "~/.dotfiles/{{ item.folder_name }}/{{ item.path }}"


- name: Generate configs (files from template)
  notify: restow dotfiles
  become_user: "{{ user }}"
  template:
    src: "{{ item.src }}"
    dest: "/home/{{ user }}/.dotfiles/{{ item.folder_name }}/{{ item.path }}"
  loop: "{{ (file_templates | default([])) | selectattr('state', 'equalto', 'file') | list }}"
  loop_control:
    label: "~/.dotfiles/{{ item.folder_name }}/{{ item.path }}"
