---
- name: Gathering user
  set_fact:
    user: "{{ ansible_facts.env.SUDO_USER | default(ansible_facts.env.USER) }}"


- name: Copy all maven scripts
  copy:
    src: "{{ role_path }}/scripts/"
    dest: "/home/{{ user }}/.local/bin/"
    mode: 0755
