---
- name: Install Flatpak
  become: yes
  apt:
    name: flatpak
    state: present
    update_cache: yes

- name: Check if OBS Studio (Flatpak) is installed
  command: flatpak --user info --show-commit com.obsproject.Studio
  register: has_obs_flatpak
  changed_when: false
  failed_when: false


- name: Add flathub remote to Flatpak
  command:
    cmd: flatpak --user remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
  register: flatpak_remote_add
  changed_when: "'configured' in flatpak_remote_add.stdout or flatpak_remote_add.rc == 0"
  when: has_obs_flatpak.rc != 0


- name: Install OBS Studio (Flatpak)
  command: >
    flatpak --user install -y flathub com.obsproject.Studio
  environment:
    FLATPAK_NONINTERACTIVE: "1"
  register: flatpak_obs_install
  changed_when: "'installed' in flatpak_obs_install.stdout
                 or 'upgraded' in flatpak_obs_install.stdout
                 or flatpak_obs_install.rc == 0"
  when: has_obs_flatpak.rc != 0


- name: Revert OBS Studio to 31.1.2 (Flatpak)
  command: >
    flatpak --user update -y --commit=4249e4245f75bbec5ad89a4bcfb2726ecbe54c7f3a642e6dbe2820ff4ac2dbc9 com.obsproject.Studio
  environment:
    FLATPAK_NONINTERACTIVE: "1"
  register: flatpak_obs_install
  changed_when: "'installed' in flatpak_obs_install.stdout
                 or 'upgraded' in flatpak_obs_install.stdout
                 or flatpak_obs_install.rc == 0"
  when: has_obs_flatpak.rc != 0 


- name: Disable updates to OBS Studio (Flatpak)
  command: >
    flatpak --user mask com.obsproject.Studio
  environment:
    FLATPAK_NONINTERACTIVE: "1"
  register: flatpak_obs_install
  changed_when: "'installed' in flatpak_obs_install.stdout
                 or 'upgraded' in flatpak_obs_install.stdout
                 or flatpak_obs_install.rc == 0"
  when: has_obs_flatpak.rc != 0


- name: Check OBS Studio (Flatpak) shortcut exists
  stat:
    path: "{{ ansible_env.HOME }}/.local/share/flatpak/app/com.obsproject.Studio/current/active/export/share/applications/com.obsproject.Studio.desktop"
  register: obs_shortcut


#
#  @note: 
#   - path to files is in ~/.local/share/flatpak/app/com.obsproject.Studio/current/active/files/
#   - you have to use propietary nvidia for obs. Nouveau or NVK seem to crash X11
#      - use below commands in order
#
#   sudo sed -i 's/main/main non-free contrib/g' /etc/apt/sources.list
#   sudo apt install linux-image-amd64 linux-headers-amd64   ## required else `sudo dkms status` wont show `installed`
#   sudo apt install nvidia-driver
#
#
- name: Update OBS Studio (Flatpak) shortcut
  copy:
    dest: "{{ ansible_env.HOME }}/.local/share/flatpak/app/com.obsproject.Studio/current/active/export/share/applications/com.obsproject.Studio.desktop"
    mode: "0600"
    content: |
      #!/usr/bin/env xdg-open
      [Desktop Entry]
      Version=1.0
      Type=Application
      Name=OBS Studio
      Exec=flatpak --user run --branch=stable --arch=x86_64 --command=obs com.obsproject.Studio --disable-shutdown-check
      Icon=com.obsproject.Studio
      Terminal=false
      Categories=AudioVideo;Recorder;Video;Streaming;
      StartupWMClass=com.obsproject.Studio
  when: obs_shortcut.stat.exists
