---
- name: Ensure Nomacs directory
  file:
    path: "/opt/nomacs"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    mode: "0755"

- name: Updating config files
  template:
    src: "{{ role_path }}/config/settings.ini"
    dest: >-
      {{ ansible_env.HOME }}/.config/nomacs/Image Lounge.conf
    mode: "0664"
    force: false
