---
- name: Check nomacs
  stat:
    path: /opt/nomacs/nomacs-x86_64.AppImage
  register: install_binary


- name: Install nomacs
  block:
    - name: Ensure nomacs directory
      become: true
      file:
        path: /opt/nomacs
        state: directory
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_gid }}"

    - name: Install Nomacs
      unarchive:
        src: https://github.com/nomacs/nomacs/releases/download/3.22.0/nomacs-3.22.0-linux-24.04-x86_64-AppImage.zip
        dest: "/opt/nomacs"
        remote_src: true

  when: not install_binary.stat.exists
