---
- name: Add Google Chrome repo
  become: true
  block:
    - name: Ensure keyring folder exist
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: 0755

    # deps for deb822_repository module
    - name: Installing dependencies
      apt:
        pkg:
          - python3-debian
          - python3-apt
        state: present
        update_cache: yes

    - name: "[TRANSIENT] Gathering repo key"
      get_url:
        url: https://dl.google.com/linux/linux_signing_key.pub
        dest: /etc/apt/keyrings/google-linux-signing-key.pub
        mode: '0644'

    - name: Creating gpg key
      command:
        cmd: >
          gpg --dearmor
          --output /etc/apt/keyrings/google-linux-signing-key.gpg
          /etc/apt/keyrings/google-linux-signing-key.pub
      args:
        creates: /etc/apt/keyrings/google-linux-signing-key.gpg

    - name: "[TRANSIENT] Cleanup leftover key file"
      ansible.builtin.file:
        path: /etc/apt/keyrings/google-linux-signing-key.pub
        state: absent

    - name: Adding chrome repo
      deb822_repository:
        name: google-chrome
        types:
          - deb
        uris: https://dl.google.com/linux/chrome/deb/
        suites:
          - stable
        components:
          - main
        architectures:
          - amd64
        signed_by: /etc/apt/keyrings/google-linux-signing-key.gpg
        enabled: true
        state: present


- name: Install chrome browser
  become: true
  apt:
    pkg:
      - google-chrome-stable
    update_cache: yes
    state: present

