---
- name: Install Google keys
  import_tasks: ../keys/google_keys.yml
  vars:
    output_gpg_key: gpg_key
  when: ansible_distribution == "Debian"


- name: Install chrome browser
  import_tasks: chrome.yml
  vars:
    gpg_key: "{{ gpg_key }}"
  when: ansible_distribution == "Debian"
