---
- name: Preparing NetworkManager scripts
  become: true
  file:
    path: /etc/NetworkManager/dispatcher.d
    state: directory
    owner: root
    group: root
    mode: "0755"



#
# TODO uncomment below after you have git submodule working
#

# - name: Gather NetworkManager scripts
#   find:
#     paths: "{{ role_path }}/network_scripts/"
#     file_type: file
#     recurse: true
#     hidden: true
#   register: found_files


# - name: "[TRANSIENT] Apply LF endings"
#   replace:
#     path: "{{ item.path }}"
#     regexp: "\r$"
#     replace: ""
#   loop: "{{ found_files.files | default([]) }}"
#   loop_control:
#     label: "{{ item.path }}"


# - name: Copy NetworkManager scripts
#   become: true
#   copy:
#     src: "{{ role_path }}/network_scripts/"
#     dest: "/etc/NetworkManager/dispatcher.d/"
#     owner: root
#     group: root
#     mode: "0755"
