---
- name: Install systemd-resolved
  become: true
  apt:
    pkg:
      - systemd-resolved
    state: present


- name: Gather systemd services
  ansible.builtin.service_facts:
  when: ansible_service_mgr == 'systemd'


- name: Enable systemd-resolved service
  ansible.builtin.systemd:
    name: systemd-resolved
    enabled: true
  when: "'systemd-resolved.service' in ansible_facts.services"
