---
- name: Adding Docker repo
  become: true
  deb822_repository:
    name: vscode
    types:
      - deb
    uris: https://download.docker.com/linux/debian
    suites:
      - stable
    components:
      - stable
    architectures:
      - amd64
    signed_by: "{{ docker_gpg }}"
    enabled: true
    state: present


- name: Install Docker
  become: true
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    update_cache: yes
    state: present


- name: Gathering user
  set_fact:
    user: "{{ ansible_facts.env.SUDO_USER | default(ansible_facts.env.USER) }}"


- name: Add user to docker group
  user:
    name: "{{ user }}"
    groups: docker
    append: true


- name: Enable Docker service
  systemd:
    name: docker
    enabled: true
    state: started

