- name: Preparing Docker gpg keys
  set_fact:
    docker_gpg: "/etc/apt/keyrings/docker.gpg"

- name: Add Docker gpg keys
  become: true
  block:
    - name: "[TRANSIENT] Gathering repo key"
      get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /etc/apt/keyrings/docker
        mode: '0644'

    - name: Creating gpg key
      command:
        cmd: >
          gpg --dearmor
          --output "{{ docker_gpg }}"
          /etc/apt/keyrings/docker
      args:
        creates: "{{ docker_gpg }}"

    - name: "[TRANSIENT] Cleanup leftover key file"
      file:
        path: /etc/apt/keyrings/docker
        state: absent
