- name: Preparing Google gpg keys
  set_fact:
    google_gpg: "/etc/apt/keyrings/google-linux-signing-key.gpg"

- name: Add Google gpg keys
  become: true
  block:
    - name: "[TRANSIENT] Gathering repo key"
      get_url:
        url: https://dl.google.com/linux/linux_signing_key.pub
        dest: /etc/apt/keyrings/google-linux-signing-key.pub
        mode: '0644'

    - name: Creating gpg key
      command:
        cmd: >
          gpg --dearmor
          --output "{{ google_gpg }}"
          /etc/apt/keyrings/google-linux-signing-key.pub
      args:
        creates: "{{ google_gpg }}"

    - name: "[TRANSIENT] Cleanup leftover key file"
      file:
        path: /etc/apt/keyrings/google-linux-signing-key.pub
        state: absent
