- name: Preparing Hashicorp gpg keys
  set_fact:
    hashicorp_gpg: "/etc/apt/keyrings/hashicorp-archive-keyring.gpg"

- name: Add Hashicorp gpg keys
  become: true
  block:
    - name: Check current Hashicorp keyring
      stat:
        path: "{{ hashicorp_gpg }}"
      register: hashicorp_gpg_info

    - name: Download current Hashicorp repository key
      get_url:
        url: https://apt.releases.hashicorp.com/gpg
        dest: /etc/apt/keyrings/hashicorp-archive-keyring.asc
        mode: '0644'
      register: hashicorp_key_download

    - name: Import current Hashicorp repository key
      command:
        cmd: >
          gpg --dearmor --yes
          --output "{{ hashicorp_gpg }}"
          /etc/apt/keyrings/hashicorp-archive-keyring.asc
      when:
        - hashicorp_key_download.changed or not hashicorp_gpg_info.stat.exists
