---
- name: Ensure keyring folder exist
  become: true
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: 0755


- name: Installing dependencies
  become: true
  apt:
    pkg:
      - gnupg
      - python3-debian
      - python3-apt
    state: present


- name: Install Microsoft keys
  import_tasks: ms_gpg.yml
  when: ansible_distribution == "Debian"


- name: Install Google keys
  import_tasks: google_gpg.yml
  when: ansible_distribution == "Debian"


- name: Install Third Party keys (Neovim image viewer)
  import_tasks: ueberzugpp_gpg.yml
  when: ansible_distribution == "Debian"


- name: Install Hashicorp keys
  import_tasks: hashicorp_gpg.yml
  when: ansible_distribution == "Debian"


- name: Install Docker keys
  import_tasks: docker_gpg.yml
  when: ansible_distribution == "Debian"


- name: Refresh apt package indexes after repository keys
  become: true
  apt:
    update_cache: true
  when: ansible_distribution == "Debian"
