- name: Preparing ueberzugpp gpg keys
  set_fact:
    ueberzugpp_gpg: "/etc/apt/keyrings/ueberzugpp-Release.gpg"

- name: Add Opensuse gpg keys
  become: true
  block:
    - name: "[TRANSIENT] Gathering repo key"
      get_url:
        url: https://download.opensuse.org/repositories/home:justkidding/Debian_13/Release.key
        dest: /etc/apt/keyrings/ueberzugpp-Release.key
        mode: '0644'

    - name: Creating gpg key
      command:
        cmd: >
          gpg --dearmor
          --output "{{ ueberzugpp_gpg }}"
          /etc/apt/keyrings/ueberzugpp-Release.key
      args:
        creates: "{{ ueberzugpp_gpg }}"

    - name: "[TRANSIENT] Cleanup leftover key file"
      file:
        path: /etc/apt/keyrings/ueberzugpp-Release.key
        state: absent
