---
- name: Install Neovim prerequisites
  import_tasks: prerequisites.yml
  when: ansible_distribution == "Debian"

- name: Install neovim
  import_tasks: neovim.yml
  when: ansible_distribution == "Debian"
