---
- name: Check if font {{ font }} exists or empty
  find:
    paths: "/usr/local/share/fonts/{{ font }}"
    file_type: directory
    hidden: true
  register: font_dir


- name: Create directory for {{ font }}
  become: true
  file:
    path: "/usr/local/share/fonts/{{ font }}"
    mode: 0775
    state: directory
  

- name: Download and extract {{ font }}
  become: true
  unarchive:
    src: "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/{{ font }}.tar.xz"
    dest: "/usr/local/share/fonts/{{ font }}"
    remote_src: true
  when: font_dir.matched == 0

